// County -> principal meridian for the PLSS states we serve. The BLM
// query MUST pin a meridian: the same township/range exists under more
// than one survey (Alabama has Huntsville, St. Stephens, Tallahassee, and
// a Chickasaw sliver), and a wildcard meridian lets a misread direction
// resolve to a real section in the wrong part of the state.
// Built 2026-08-20 from the BLM CadNSDI township layer intersected with
// Census TIGERweb county polygons (distinct PRINMERCD per county), then
// squared with the known survey boundaries; counties the survey line
// crosses carry alternates and certain=false. Extend by adding a state.

import { MERIDIANS } from "@/lib/plss";

export interface CountyMeridian {
  primary: string; // key in MERIDIANS (HU, SS, TA, CK, CH, WA, LA, SH, FI)
  alternates: string[];
  certain: boolean; // false when the survey boundary crosses the county
}

export const COUNTY_MERIDIANS: Record<string, Record<string, CountyMeridian>> = {
  AL: {
    "Autauga": { primary: "SS", alternates: [], certain: true },
    "Baldwin": { primary: "SS", alternates: [], certain: true },
    "Barbour": { primary: "SS", alternates: [], certain: true },
    "Bibb": { primary: "HU", alternates: ["SS"], certain: false },
    "Blount": { primary: "HU", alternates: [], certain: true },
    "Bullock": { primary: "SS", alternates: [], certain: true },
    "Butler": { primary: "SS", alternates: [], certain: true },
    "Calhoun": { primary: "HU", alternates: [], certain: true },
    "Chambers": { primary: "HU", alternates: ["SS"], certain: false },
    "Cherokee": { primary: "HU", alternates: [], certain: true },
    "Chilton": { primary: "SS", alternates: [], certain: true },
    "Choctaw": { primary: "SS", alternates: ["CH"], certain: true },
    "Clarke": { primary: "SS", alternates: [], certain: true },
    "Clay": { primary: "HU", alternates: ["SS"], certain: false },
    "Cleburne": { primary: "HU", alternates: [], certain: true },
    "Coffee": { primary: "SS", alternates: [], certain: true },
    "Colbert": { primary: "HU", alternates: ["CK"], certain: true },
    "Conecuh": { primary: "SS", alternates: [], certain: true },
    "Coosa": { primary: "HU", alternates: ["SS"], certain: false },
    "Covington": { primary: "SS", alternates: ["TA"], certain: false },
    "Crenshaw": { primary: "SS", alternates: [], certain: true },
    "Cullman": { primary: "HU", alternates: [], certain: true },
    "Dale": { primary: "SS", alternates: [], certain: true },
    "Dallas": { primary: "SS", alternates: [], certain: true },
    "DeKalb": { primary: "HU", alternates: [], certain: true },
    "Elmore": { primary: "SS", alternates: [], certain: true },
    "Escambia": { primary: "SS", alternates: ["TA"], certain: false },
    "Etowah": { primary: "HU", alternates: [], certain: true },
    "Fayette": { primary: "HU", alternates: [], certain: true },
    "Franklin": { primary: "HU", alternates: ["CK"], certain: true },
    "Geneva": { primary: "SS", alternates: ["TA"], certain: false },
    "Greene": { primary: "SS", alternates: ["HU"], certain: false },
    "Hale": { primary: "SS", alternates: [], certain: true },
    "Henry": { primary: "SS", alternates: [], certain: true },
    "Houston": { primary: "SS", alternates: ["TA"], certain: false },
    "Jackson": { primary: "HU", alternates: [], certain: true },
    "Jefferson": { primary: "HU", alternates: ["SS"], certain: false },
    "Lamar": { primary: "HU", alternates: ["CK"], certain: true },
    "Lauderdale": { primary: "HU", alternates: ["CK"], certain: true },
    "Lawrence": { primary: "HU", alternates: [], certain: true },
    "Lee": { primary: "SS", alternates: [], certain: true },
    "Limestone": { primary: "HU", alternates: [], certain: true },
    "Lowndes": { primary: "SS", alternates: [], certain: true },
    "Macon": { primary: "SS", alternates: [], certain: true },
    "Madison": { primary: "HU", alternates: [], certain: true },
    "Marengo": { primary: "SS", alternates: [], certain: true },
    "Marion": { primary: "HU", alternates: ["CK"], certain: true },
    "Marshall": { primary: "HU", alternates: [], certain: true },
    "Mobile": { primary: "SS", alternates: [], certain: true },
    "Monroe": { primary: "SS", alternates: [], certain: true },
    "Montgomery": { primary: "SS", alternates: [], certain: true },
    "Morgan": { primary: "HU", alternates: [], certain: true },
    "Perry": { primary: "SS", alternates: [], certain: true },
    "Pickens": { primary: "HU", alternates: ["SS", "CH"], certain: false },
    "Pike": { primary: "SS", alternates: [], certain: true },
    "Randolph": { primary: "HU", alternates: ["SS"], certain: false },
    "Russell": { primary: "SS", alternates: [], certain: true },
    "Shelby": { primary: "HU", alternates: ["SS"], certain: false },
    "St. Clair": { primary: "HU", alternates: [], certain: true },
    "Sumter": { primary: "SS", alternates: ["CH"], certain: true },
    "Talladega": { primary: "HU", alternates: ["SS"], certain: false },
    "Tallapoosa": { primary: "HU", alternates: ["SS"], certain: false },
    "Tuscaloosa": { primary: "HU", alternates: ["SS"], certain: false },
    "Walker": { primary: "HU", alternates: [], certain: true },
    "Washington": { primary: "SS", alternates: [], certain: true },
    "Wilcox": { primary: "SS", alternates: [], certain: true },
    "Winston": { primary: "HU", alternates: [], certain: true },
  },
  MS: {
    "Adams": { primary: "WA", alternates: [], certain: true },
    "Alcorn": { primary: "CK", alternates: [], certain: true },
    "Amite": { primary: "WA", alternates: ["SH"], certain: false },
    "Attala": { primary: "CH", alternates: [], certain: true },
    "Benton": { primary: "CK", alternates: [], certain: true },
    "Bolivar": { primary: "CH", alternates: [], certain: true },
    "Calhoun": { primary: "CH", alternates: ["CK"], certain: false },
    "Carroll": { primary: "CH", alternates: [], certain: true },
    "Chickasaw": { primary: "CK", alternates: [], certain: true },
    "Choctaw": { primary: "CH", alternates: [], certain: false },
    "Claiborne": { primary: "WA", alternates: [], certain: true },
    "Clarke": { primary: "CH", alternates: ["SS"], certain: false },
    "Clay": { primary: "CH", alternates: ["CK", "HU"], certain: false },
    "Coahoma": { primary: "CH", alternates: ["CK"], certain: false },
    "Copiah": { primary: "CH", alternates: ["SS", "WA"], certain: false },
    "Covington": { primary: "SS", alternates: [], certain: true },
    "DeSoto": { primary: "CK", alternates: [], certain: false },
    "Forrest": { primary: "SS", alternates: [], certain: true },
    "Franklin": { primary: "WA", alternates: [], certain: true },
    "George": { primary: "SS", alternates: [], certain: true },
    "Greene": { primary: "SS", alternates: [], certain: true },
    "Grenada": { primary: "CH", alternates: [], certain: true },
    "Hancock": { primary: "SS", alternates: ["SH"], certain: false },
    "Harrison": { primary: "SS", alternates: ["SH"], certain: false },
    "Hinds": { primary: "CH", alternates: ["WA"], certain: false },
    "Holmes": { primary: "CH", alternates: [], certain: true },
    "Humphreys": { primary: "CH", alternates: [], certain: true },
    "Issaquena": { primary: "CH", alternates: ["WA"], certain: false },
    "Itawamba": { primary: "CK", alternates: ["HU"], certain: false },
    "Jackson": { primary: "SS", alternates: [], certain: true },
    "Jasper": { primary: "CH", alternates: ["SS"], certain: false },
    "Jefferson": { primary: "WA", alternates: [], certain: true },
    "Jefferson Davis": { primary: "SS", alternates: [], certain: true },
    "Jones": { primary: "SS", alternates: [], certain: true },
    "Kemper": { primary: "CH", alternates: ["SS"], certain: false },
    "Lafayette": { primary: "CK", alternates: [], certain: false },
    "Lamar": { primary: "SS", alternates: [], certain: true },
    "Lauderdale": { primary: "CH", alternates: ["SS"], certain: false },
    "Lawrence": { primary: "SS", alternates: ["WA"], certain: false },
    "Leake": { primary: "CH", alternates: [], certain: true },
    "Lee": { primary: "CK", alternates: [], certain: true },
    "Leflore": { primary: "CH", alternates: [], certain: true },
    "Lincoln": { primary: "WA", alternates: [], certain: true },
    "Lowndes": { primary: "CH", alternates: ["CK", "HU"], certain: false },
    "Madison": { primary: "CH", alternates: [], certain: false },
    "Marion": { primary: "SS", alternates: ["WA", "SH"], certain: false },
    "Marshall": { primary: "CK", alternates: [], certain: false },
    "Monroe": { primary: "CK", alternates: ["HU"], certain: false },
    "Montgomery": { primary: "CH", alternates: [], certain: false },
    "Neshoba": { primary: "CH", alternates: [], certain: true },
    "Newton": { primary: "CH", alternates: [], certain: true },
    "Noxubee": { primary: "CH", alternates: ["SS", "HU"], certain: false },
    "Oktibbeha": { primary: "CH", alternates: ["CK"], certain: false },
    "Panola": { primary: "CH", alternates: ["CK"], certain: false },
    "Pearl River": { primary: "SS", alternates: ["SH"], certain: false },
    "Perry": { primary: "SS", alternates: [], certain: true },
    "Pike": { primary: "WA", alternates: ["SH"], certain: false },
    "Pontotoc": { primary: "CK", alternates: [], certain: false },
    "Prentiss": { primary: "CK", alternates: [], certain: true },
    "Quitman": { primary: "CH", alternates: ["CK"], certain: false },
    "Rankin": { primary: "CH", alternates: [], certain: true },
    "Scott": { primary: "CH", alternates: [], certain: true },
    "Sharkey": { primary: "CH", alternates: [], certain: true },
    "Simpson": { primary: "CH", alternates: ["SS", "WA"], certain: false },
    "Smith": { primary: "CH", alternates: ["SS"], certain: false },
    "Stone": { primary: "SS", alternates: [], certain: true },
    "Sunflower": { primary: "CH", alternates: [], certain: true },
    "Tallahatchie": { primary: "CH", alternates: ["CK"], certain: false },
    "Tate": { primary: "CK", alternates: [], certain: true },
    "Tippah": { primary: "CK", alternates: [], certain: false },
    "Tishomingo": { primary: "CK", alternates: ["HU"], certain: false },
    "Tunica": { primary: "CH", alternates: ["CK"], certain: false },
    "Union": { primary: "CK", alternates: [], certain: false },
    "Walthall": { primary: "WA", alternates: ["SH"], certain: false },
    "Warren": { primary: "CH", alternates: ["WA"], certain: false },
    "Washington": { primary: "CH", alternates: [], certain: true },
    "Wayne": { primary: "CH", alternates: ["SS"], certain: false },
    "Webster": { primary: "CH", alternates: [], certain: false },
    "Wilkinson": { primary: "WA", alternates: [], certain: false },
    "Winston": { primary: "CH", alternates: [], certain: true },
    "Yalobusha": { primary: "CH", alternates: ["CK"], certain: false },
    "Yazoo": { primary: "CH", alternates: ["WA"], certain: false },
  },
  FL: {
    "Alachua": { primary: "TA", alternates: [], certain: true },
    "Baker": { primary: "TA", alternates: [], certain: true },
    "Bay": { primary: "TA", alternates: [], certain: true },
    "Bradford": { primary: "TA", alternates: [], certain: true },
    "Brevard": { primary: "TA", alternates: [], certain: true },
    "Broward": { primary: "TA", alternates: [], certain: true },
    "Calhoun": { primary: "TA", alternates: [], certain: true },
    "Charlotte": { primary: "TA", alternates: [], certain: true },
    "Citrus": { primary: "TA", alternates: [], certain: true },
    "Clay": { primary: "TA", alternates: [], certain: true },
    "Collier": { primary: "TA", alternates: [], certain: true },
    "Columbia": { primary: "TA", alternates: [], certain: true },
    "DeSoto": { primary: "TA", alternates: [], certain: true },
    "Dixie": { primary: "TA", alternates: [], certain: true },
    "Duval": { primary: "TA", alternates: [], certain: true },
    "Escambia": { primary: "TA", alternates: [], certain: true },
    "Flagler": { primary: "TA", alternates: [], certain: true },
    "Franklin": { primary: "TA", alternates: [], certain: true },
    "Gadsden": { primary: "TA", alternates: [], certain: true },
    "Gilchrist": { primary: "TA", alternates: [], certain: true },
    "Glades": { primary: "TA", alternates: [], certain: true },
    "Gulf": { primary: "TA", alternates: [], certain: true },
    "Hamilton": { primary: "TA", alternates: [], certain: true },
    "Hardee": { primary: "TA", alternates: [], certain: true },
    "Hendry": { primary: "TA", alternates: [], certain: true },
    "Hernando": { primary: "TA", alternates: [], certain: true },
    "Highlands": { primary: "TA", alternates: [], certain: true },
    "Hillsborough": { primary: "TA", alternates: [], certain: true },
    "Holmes": { primary: "TA", alternates: [], certain: true },
    "Indian River": { primary: "TA", alternates: [], certain: true },
    "Jackson": { primary: "TA", alternates: [], certain: true },
    "Jefferson": { primary: "TA", alternates: [], certain: true },
    "Lafayette": { primary: "TA", alternates: [], certain: true },
    "Lake": { primary: "TA", alternates: [], certain: true },
    "Lee": { primary: "TA", alternates: [], certain: true },
    "Leon": { primary: "TA", alternates: [], certain: true },
    "Levy": { primary: "TA", alternates: [], certain: true },
    "Liberty": { primary: "TA", alternates: [], certain: true },
    "Madison": { primary: "TA", alternates: [], certain: true },
    "Manatee": { primary: "TA", alternates: [], certain: true },
    "Marion": { primary: "TA", alternates: [], certain: true },
    "Martin": { primary: "TA", alternates: [], certain: true },
    "Miami-Dade": { primary: "TA", alternates: [], certain: true },
    "Monroe": { primary: "TA", alternates: [], certain: true },
    "Nassau": { primary: "TA", alternates: [], certain: true },
    "Okaloosa": { primary: "TA", alternates: [], certain: true },
    "Okeechobee": { primary: "TA", alternates: [], certain: true },
    "Orange": { primary: "TA", alternates: [], certain: true },
    "Osceola": { primary: "TA", alternates: [], certain: true },
    "Palm Beach": { primary: "TA", alternates: [], certain: true },
    "Pasco": { primary: "TA", alternates: [], certain: true },
    "Pinellas": { primary: "TA", alternates: [], certain: true },
    "Polk": { primary: "TA", alternates: [], certain: true },
    "Putnam": { primary: "TA", alternates: [], certain: true },
    "Santa Rosa": { primary: "TA", alternates: [], certain: true },
    "Sarasota": { primary: "TA", alternates: [], certain: true },
    "Seminole": { primary: "TA", alternates: [], certain: true },
    "St. Johns": { primary: "TA", alternates: [], certain: true },
    "St. Lucie": { primary: "TA", alternates: [], certain: true },
    "Sumter": { primary: "TA", alternates: [], certain: true },
    "Suwannee": { primary: "TA", alternates: [], certain: true },
    "Taylor": { primary: "TA", alternates: [], certain: true },
    "Union": { primary: "TA", alternates: [], certain: true },
    "Volusia": { primary: "TA", alternates: [], certain: true },
    "Wakulla": { primary: "TA", alternates: [], certain: true },
    "Walton": { primary: "TA", alternates: [], certain: true },
    "Washington": { primary: "TA", alternates: [], certain: true },
  },
  LA: {
    "Acadia": { primary: "LA", alternates: [], certain: true },
    "Allen": { primary: "LA", alternates: [], certain: true },
    "Ascension": { primary: "LA", alternates: ["SH"], certain: false },
    "Assumption": { primary: "LA", alternates: [], certain: true },
    "Avoyelles": { primary: "LA", alternates: [], certain: true },
    "Beauregard": { primary: "LA", alternates: [], certain: true },
    "Bienville": { primary: "LA", alternates: [], certain: true },
    "Bossier": { primary: "LA", alternates: [], certain: true },
    "Caddo": { primary: "LA", alternates: [], certain: true },
    "Calcasieu": { primary: "LA", alternates: [], certain: true },
    "Caldwell": { primary: "LA", alternates: [], certain: true },
    "Cameron": { primary: "LA", alternates: [], certain: true },
    "Catahoula": { primary: "LA", alternates: [], certain: true },
    "Claiborne": { primary: "LA", alternates: [], certain: true },
    "Concordia": { primary: "LA", alternates: [], certain: true },
    "De Soto": { primary: "LA", alternates: [], certain: true },
    "East Baton Rouge": { primary: "SH", alternates: ["LA"], certain: false },
    "East Carroll": { primary: "LA", alternates: [], certain: true },
    "East Feliciana": { primary: "SH", alternates: [], certain: true },
    "Evangeline": { primary: "LA", alternates: [], certain: true },
    "Franklin": { primary: "LA", alternates: [], certain: true },
    "Grant": { primary: "LA", alternates: [], certain: true },
    "Iberia": { primary: "LA", alternates: [], certain: true },
    "Iberville": { primary: "LA", alternates: ["SH"], certain: false },
    "Jackson": { primary: "LA", alternates: [], certain: true },
    "Jefferson": { primary: "LA", alternates: ["SH"], certain: false },
    "Jefferson Davis": { primary: "LA", alternates: [], certain: true },
    "LaSalle": { primary: "LA", alternates: [], certain: true },
    "Lafayette": { primary: "LA", alternates: [], certain: true },
    "Lafourche": { primary: "LA", alternates: [], certain: true },
    "Lincoln": { primary: "LA", alternates: [], certain: true },
    "Livingston": { primary: "SH", alternates: [], certain: true },
    "Madison": { primary: "LA", alternates: [], certain: true },
    "Morehouse": { primary: "LA", alternates: [], certain: true },
    "Natchitoches": { primary: "LA", alternates: [], certain: true },
    "Orleans": { primary: "SH", alternates: ["LA"], certain: false },
    "Ouachita": { primary: "LA", alternates: [], certain: true },
    "Plaquemines": { primary: "LA", alternates: ["SH"], certain: false },
    "Pointe Coupee": { primary: "LA", alternates: ["SH"], certain: false },
    "Rapides": { primary: "LA", alternates: [], certain: true },
    "Red River": { primary: "LA", alternates: [], certain: true },
    "Richland": { primary: "LA", alternates: [], certain: true },
    "Sabine": { primary: "LA", alternates: [], certain: true },
    "St. Bernard": { primary: "SH", alternates: [], certain: true },
    "St. Charles": { primary: "LA", alternates: ["SH"], certain: false },
    "St. Helena": { primary: "SH", alternates: [], certain: true },
    "St. James": { primary: "LA", alternates: ["SH"], certain: false },
    "St. John the Baptist": { primary: "LA", alternates: ["SH"], certain: false },
    "St. Landry": { primary: "LA", alternates: [], certain: true },
    "St. Martin": { primary: "LA", alternates: [], certain: true },
    "St. Mary": { primary: "LA", alternates: [], certain: true },
    "St. Tammany": { primary: "SH", alternates: [], certain: true },
    "Tangipahoa": { primary: "SH", alternates: [], certain: true },
    "Tensas": { primary: "LA", alternates: [], certain: true },
    "Terrebonne": { primary: "LA", alternates: [], certain: true },
    "Union": { primary: "LA", alternates: [], certain: true },
    "Vermilion": { primary: "LA", alternates: [], certain: true },
    "Vernon": { primary: "LA", alternates: [], certain: true },
    "Washington": { primary: "SH", alternates: [], certain: true },
    "Webster": { primary: "LA", alternates: [], certain: true },
    "West Baton Rouge": { primary: "LA", alternates: ["SH"], certain: false },
    "West Carroll": { primary: "LA", alternates: [], certain: true },
    "West Feliciana": { primary: "LA", alternates: ["SH"], certain: false },
    "Winn": { primary: "LA", alternates: [], certain: true },
  },
};
export function normalizeCounty(raw: string | null | undefined): string {
  return String(raw ?? "")
    .toLowerCase()
    .replace(/\b(county|parish|co\.?)\b/g, "")
    .replace(/[^a-z]/g, "");
}

export interface MeridianResolution {
  primary: string | null;
  alternates: string[];
  certain: boolean;
  // Every meridian key surveyed in the state, for the unknown-county
  // case and the retry chips.
  stateMeridians: string[];
}

// Meridian for a deed's county. Unknown county: no primary; the caller
// must ask (never query without one). Unknown state: nothing at all.
export function meridiansForCounty(
  state: string | null | undefined,
  county: string | null | undefined
): MeridianResolution {
  const st = String(state ?? "").toUpperCase();
  const byCounty = COUNTY_MERIDIANS[st];
  const stateMeridians = byCounty
    ? [...new Set(Object.values(byCounty).flatMap((v) => [v.primary, ...v.alternates]))].filter(
        (k) => MERIDIANS[k]
      )
    : [];
  if (!byCounty) return { primary: null, alternates: [], certain: false, stateMeridians };
  const want = normalizeCounty(county);
  if (!want) return { primary: null, alternates: [], certain: false, stateMeridians };
  const hit = Object.entries(byCounty).find(([name]) => normalizeCounty(name) === want);
  if (!hit) return { primary: null, alternates: [], certain: false, stateMeridians };
  return { ...hit[1], stateMeridians };
}

export const PLSS_STATES = Object.keys(COUNTY_MERIDIANS);
